version: '3'

services:

  redis:
    image: redislabs/rejson
    ports:
      - 6382:6379
​
  main_server:
    image: geospatialdatastore_main_server:version1
    build: main_server/
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    links:
      - redis
    depends_on:
      - redis
    environment:
      REDIS_URL: redis:6379
    volumes:
      - .:/go/src/main_server
    ports:
      - 3030:3001

  web_server:
    image: geospatialdatastore_web_server:version1
    build: web_server/
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    volumes:

      - .:/go/src/web_server
    ports:
      - 12346:12345

  potree:
    image: apache
    build: ./potree_entwine
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure

    # depends_on:
    #   # - entwine_build
    #   - entwine_serve
    # container_name: potree_web
    restart: always
    ports:
      - "8085:80"

  entwine_conda:
    image: continuumio/miniconda
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M

      restart_policy:
        condition: on-failure

    volumes:
      - .:/code2/geoHub

    command: >
      bash -c " conda install nodejs -y
      && npm install http-server -g
      && http-server code2/geoHub/entwine/entwine -p 8089 --cors"

    ports:
      - "8111:8089"

​