FROM openjdk:8-jdk-alpine

# Required for starting application up.
RUN apk update && apk add bash

RUN mkdir -p /opt/app
ENV PROJECT_HOME /opt/app

VOLUME /tmp
COPY build/libs/web_server-spring-0.1.0.jar $PROJECT_HOME/web_server-spring-0.1.0.jar

WORKDIR $PROJECT_HOME
# ENTRYPOINT ["java","-jar","/app.jar"]
CMD ["java", "-Dspring.data.mongodb.uri=mongodb://springboot-mongo:27017/spring<->mongo","-Djava.security.egd=file:/dev/./urandom","-jar","./web_server-spring-0.1.0.jar"]