FROM golang:alpine
RUN apk add git

COPY . /go/src/main_server/
RUN go get -u github.com/gorilla/mux
RUN go get /go/src/main_server
RUN echo "installed main server"
WORKDIR /go/src/main_server

ENTRYPOINT /go/bin/main_server